url: https://spacewalkpublishing.us
baseurl:

# Site settings
title: Spacewalk Publishing
email: inquiries@spacewalkpublishing.us
description: "Tell amazing stories. Independent media house based out of Melbourne, FL. Creators for page, stage, screen, and speaker."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 375a7f
  secondary: c14b4e
  secondary-dark: 740a0c

# Team names, titles and social links
people:
- name: Casey Doran
  pic: cas
  position: Operations
  social:
    - title: github
      url: http://github.com/elementc/
    - title: twitter
      url: http://twitter.com/CaseyDoran/

- name: Jacob Fjeldheim
  pic: fjeld
  position: Music
  social:
    - title: envelope
      url: mailto:fjeldheim.j@gmail.com
    - title: twitter
      url: https://twitter.com/thefjeld

- name: Tyler Kerstetter
  pic: kerst
  position: Scripts
  social:
    - title: space-shuttle
      url: #

- name: Jackson Smith
  pic: jax
  position: Prose
  social:
    - title: rss
      url: http://pixel-scribe.com/
    - title: twitter
      url: https://twitter.com/PixlScrib

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/spacewalkpubl
  - title: facebook
    url: http://facebook.com/spacewalkpubl

# Postal address (add as many lines as necessary)
address:
  - line: Melbourne, FL 32901

# Build settings
markdown: kramdown
permalink: pretty
