url: https://spacewalkpublishing.github.io
baseurl:

# Site settings
title: Spacewalk Publishing
email: info@spacewalkpublishing.us
description: "Tell amazing stories. Independent media house based out of Melbourne, FL. Creators for page, stage, screen, and speaker."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 375a7f
  secondary: c14b4e
  secondary-dark: 740a0c

# Team names, titles and social links
people:
- name: Casey Doran
  pic: cas
  position: Operations Officer
  social:
    - title: twitter
      url: http://twitter.com/CaseyDoran/

- name: Jacob Fjeldheim
  pic: fjeld
  position: Music Officer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Tyler Kerstetter
  pic: kerst
  position: Script Officer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Jackson Smith
  pic: jax
  position: Prose Officer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/spacewalkpubl
  - title: facebook
    url: http://facebook.com/spacewalkpubl

# Postal address (add as many lines as necessary)
address:
  - line: Melbourne, FL 32901

# Build settings
markdown: kramdown
permalink: pretty
